# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RasterVision
                                 A QGIS plugin
 Work with Raster Vision data in QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RasterVision class from file RasterVision.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .raster_vision import RasterVisionPlugin
    return RasterVisionPlugin(iface)
